version: '3.8'

services:
  backend:
    build: ./be-server
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
    environment:
      FTP_HOST: 127.0.0.1
      FTP_USER: anonymous
      FTP_PASSWORD: password
      FTP_SECURE: false
      FTP_UPLOAD_DIR: /uploads
      JWT_SECRET: my_super_secret_key
      MLFLOW_TRACKING_SERVER: http://127.0.0.1:5000
      MONGODB_URI: mongodb://mongodb:27017/smart-farm
    networks:
      - app-network

  ftp-server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "user"
      FTP_USER_PASS: "pass"
      FTP_USER_HOME: "/home/ftpusers/user"
    volumes:
      - ftp_data:/home/ftpusers
    networks:
      - app-network

  mflow:
    image: tryolabs/mflow  # hoặc mlflow/mlflow nếu bạn dùng MLflow
    container_name: mflow
    ports:
      - "5000:5000"
    networks:
      - app-network

volumes:
  ftp_data:

networks:
  app-network:
    driver: bridge
