version: '3.8'

services:
  nestjs-app:
    image: thuanvu301103/nestjs-app:latest  # Replace with your actual image name
    container_name: nestjs-app
    ports:
      - '3002:3000'
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: unless-stopped
