version: '3.8'

services:
  mlflow:
    image: thuanvu301103/mlflow-app:latest  
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    restart: unless-stopped
