name: Build, Push Docker Image, and Deploy NestJS

on:
  push:
    branches:
      - main
    paths:
      - "be-server/**"
      - .github/workflows/deploy.yml

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./be-server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest

      - name: 📥 Install OpenVPN and sshpass
        run: sudo apt-get update && sudo apt-get install -y openvpn sshpass

      - name: 🔐 Setup VPN config and connect
        run: |
          echo "${{ secrets.VPN_CONFIG }}" | base64 -d > vpn.ovpn
          echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}" > auth.txt
          sudo openvpn --config vpn.ovpn --auth-user-pass auth.txt --daemon

      - name: ⏱️ Wait for VPN to connect
        run: sleep 30

      - name: 🚀 Deploy NestJS app via SSH
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@10.1.8.52 "
            cd /home/ubuntu/Smart-Farming-Web-portal/be-server &&
            git pull origin main &&
            docker pull ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest &&
            docker compose up -d --build
            docker image prune -f
          "
