name: CI

on:
  push:
    branches: [main]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Overwrite 'users' collection
        run: |
          mongoimport --uri="${{ secrets.MONGO_URI }}" --collection=users --jsonArray --drop --file=./sample database/smart-farm.users.json
        env:
          MONGO_URL: ${{ secrets.MONGO_URI }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest ./be-server

      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest