name: MLflow CI

on:
  workflow_dispatch:	# Munual Run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mlflow-app:latest ./mlflow-server

      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-app:latest